In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### Entrenador.csv

In [40]:
df1 = pd.read_csv('data/entrenador.csv')
df1.head(10)

,idEntrenador,Pais,Apodo,Nombre,T,PJ,PG,PE,PP,%
0,1,NaN,Ferguson,Alexander Chapman Ferguson,22,214,115,56,43,53%26%21%
1,2,NaN,Wenger,Arsène Charles Ernest Wenger,21,208,103,45,60,49%21%30%
2,3,NaN,Ancelotti,Carlo Michel Angelo Ancelotti,21,204,119,43,42,58%21%21%
3,4,NaN,Lucescu,Mircea Lucescu,20,152,59,36,57,38%23%39%
4,5,NaN,Mourinho,José Mário dos Santos Mourinho Félix,17,151,81,36,34,53%23%24%
5,6,NaN,Guardiola,Josep Guardiola Sala,15,172,111,34,27,64%19%17%
6,7,NaN,Trapattoni,Giovanni Trapattoni,13,82,40,20,22,48%24%28%
7,8,NaN,Miguel Muñoz,Miguel Muñoz Mozún,13,71,41,10,20,57%14%29%
8,9,NaN,Lobanovskyi,Valeriy Vasylyovych Lobanovskyi,12,96,46,22,28,47%22%31%
9,10,NaN,Benítez,Rafael Benítez Maudes,12,111,63,24,24,56%21%23%

In [41]:
#Diccionario entrenadores
diccionario_entrenadores = df1.set_index('Apodo')['idEntrenador'].to_dict()
print(diccionario_entrenadores)

{'Ferguson': 1, 'Wenger': 2, 'Ancelotti': 3, 'Lucescu': 4, 'Mourinho': 5, 'Guardiola': 6, 'Trapattoni': 7, 'Miguel Muñoz': 8, 'Lobanovskyi': 9, 'Benítez': 10, 'Simeone': 11, 'Spalletti': 12, 'Allegri': 13, 'Smith': 14, 'Bajević': 15, 'Jorge Jesus': 16, 'Hiddink': 17, 'Klopp': 18, 'Hitzfeld': 19, 'Romantsev': 20, 'Koeman': 21, 'Fatih Terim': 22, 'Jock Stein': 23, 'Bogs': 24, 'Van Gaal': 25, 'Gurbanov': 26, 'Solbakken': 27, 'Ivić': 28, 'Happel': 29, 'Mancini': 30, 'Goncharenko': 31, 'Batteux': 32, 'Schmidt': 33, 'Lattek': 34, 'Capello': 35, 'Lippi': 36, 'Emery': 37, 'Beenhakker': 38, 'Jesualdo Ferreira': 39, 'Skovdahl': 40, 'Daum': 41, 'Paisley': 42, 'Vrba': 43, 'Stanković': 223, 'Milev': 45, 'Tuchel': 46, 'Gross': 47, 'Sérgio Conceição': 48, 'Gazzaev': 49, 'Valverde': 50, 'Pellegrini': 51, 'Heynckes': 52, 'Favre': 53, 'Gerets': 54, 'Miljanić': 55, 'Deschamps': 56, 'Hrygorchuk': 57, 'Guðjónsson': 58, 'Otto Glória': 59, 'Nagelsmann': 60, 'Rudi Garcia': 61, 'Sollied': 62, 'Lopetegui': 63, 'Barić': 64, 'McLaughlin': 65, 'Scot Symon': 66, 'Conte': 67, 'Frank de Boer': 68, 'Jardim': 69, 'Pochettino': 70, 'Puel': 71, 'Schaaf': 72, 'Goethals': 73, 'Ranieri': 74, 'Kuchuk': 75, 'Bobby Robson': 76, 'Stevens': 77, 'Slutski': 78, 'Rose': 79, 'Lennon': 80, 'Toshack': 81, 'Fernando Santos': 82, 'Bobek': 83, 'Rui Vitória': 84, 'Kenny': 85, 'Busby': 86, 'Rinus Michels': 87, 'Solskjær': 88, 'Helenio Herrera': 89, 'Lemonis': 90, 'Semin': 91, 'Nicușor': 92, 'Houllier': 93, 'Magath': 94, 'Weiss': 95, 'Blanc': 96, 'Rodgers': 97, 'Ten Hag': 98, 'Advocaat': 99, 'Healy': 100, 'Zidane': 101, 'Irureta': 102, 'Cheburin': 103, 'Eriksson': 104, 'Cruyff': 105, 'Milanič': 106, 'Artur Jorge': 107, 'Vítor Pereira': 108, 'Güneş': 109, 'Denizli': 110, 'Serra Ferrer': 111, 'Fenlon': 112, 'Rebrov': 113, 'Osim': 185, 'Boškov': 115, 'Co Adriaanse': 116, 'Jarolím': 117, 'Koskela': 118, 'Houghton': 119, 'Vercauteren': 120, 'Seoane': 121, 'Strachan': 122, 'Ježek': 123, 'Del Bosque': 124, 'Merkel': 125, 'Skibbe': 126, 'Ten Cate': 127, 'Berdyev': 128, 'Broos': 129, 'Trpišovský': 130, 'Fischer': 131, 'Clough': 132, 'Jovanović': 133, 'Cocu': 134, 'Šimundža': 135, 'Gasperini': 136, 'Petrescu': 137, 'Pioli': 138, 'Petrović': 139, 'Katalinić': 140, 'Carniglia': 141, 'Rijkaard': 142, 'Inzaghi': 143, "O'Neill": 144, 'Sarri': 145, 'Levy': 146, 'Luis Enrique': 147, 'Paulo Fonseca': 148, 'Weisweiler': 149, 'Gress': 150, 'Bjelica': 151, 'Souness': 152, 'Van den Brom': 153, "Preud'homme": 154, 'Semak': 155, 'Boskamp': 156, 'McNeill': 157, 'Clément': 158, 'Zaccheroni': 159, 'Cúper': 160, 'Pedro Martins': 161, 'Bosz': 162, 'Jacobs': 163, 'Özyazıcı': 164, 'Sing': 165, 'Blaževic': 166, 'Paulo Bento': 167, 'Snella': 168, 'Iordănescu': 169, 'Van Bommel': 170, 'Herbin': 171, 'Villas-Boas': 172, 'Nikolić': 173, 'Krügel': 174, 'Cramer': 175, 'Donis': 176, 'Milne': 177, 'Keßler': 178, 'De Mos': 179, 'Jiménez': 180, 'Hasi': 181, 'Hütter': 182, 'Jacquet': 183, 'Jurčić': 184, 'Dermendzhiev': 186, 'Di Matteo': 187, 'Prandelli': 188, 'Csernai': 189, 'Paulo Sousa': 190, 'Josa': 191, 'Jokanović': 192, 'Skorża': 193, 'Keller': 194, 'Chovanec': 195, 'Stoilov': 196, 'Carrera': 197, 'Stoev': 198, 'Koller': 199, 'Rijvers': 200, 'Doll': 201, 'Khatskevich': 202, 'Puskás': 203, 'Baup': 204, 'Sacchi': 205, 'Toppmöller': 206, 'Lehkosuo': 207, 'Leekens': 208, 'Vičan': 209, 'Ingebrigtsen': 210, 'Hof': 211, 'Leduc': 212, 'Parola': 213, 'Kovács': 214, 'Riera': 215, 'Čačić': 216, 'Jaime Pacheco': 217, 'Hagi': 218, 'Bílek': 219, 'Van Marwijk': 220, 'Oliveira': 221, 'Guttmann': 222, 'Zekić': 224, 'Lampard': 225, 'Cherchesov': 226, 'Bukovi': 227, 'Terzić': 228, 'Bradley': 229, 'Scala': 230, 'Haan': 231, 'Sinibaldi': 232, 'Okan': 233, 'Bakhar': 234, 'Xavi': 235, 'Broćić': 236, 'Vengloš': 237, 'Wicky': 238, 'Pavić': 239, 'Stoichiță': 240, 'Frühwirth': 241, 'Antić': 242, 'Backe': 243, 'Rehhagel': 244, 'Sammer': 245, 'Weiler': 246, 'Tumbaković': 247, 'McLeish': 248, 'Camacho': 249, 'Rocco': 250}

In [42]:
df1.drop(['Pais'], axis=1, inplace=True)
df1.head(10)

,idEntrenador,Apodo,Nombre,T,PJ,PG,PE,PP,%
0,1,Ferguson,Alexander Chapman Ferguson,22,214,115,56,43,53%26%21%
1,2,Wenger,Arsène Charles Ernest Wenger,21,208,103,45,60,49%21%30%
2,3,Ancelotti,Carlo Michel Angelo Ancelotti,21,204,119,43,42,58%21%21%
3,4,Lucescu,Mircea Lucescu,20,152,59,36,57,38%23%39%
4,5,Mourinho,José Mário dos Santos Mourinho Félix,17,151,81,36,34,53%23%24%
5,6,Guardiola,Josep Guardiola Sala,15,172,111,34,27,64%19%17%
6,7,Trapattoni,Giovanni Trapattoni,13,82,40,20,22,48%24%28%
7,8,Miguel Muñoz,Miguel Muñoz Mozún,13,71,41,10,20,57%14%29%
8,9,Lobanovskyi,Valeriy Vasylyovych Lobanovskyi,12,96,46,22,28,47%22%31%
9,10,Benítez,Rafael Benítez Maudes,12,111,63,24,24,56%21%23%

#### Equipo.csv

In [20]:
df2 = pd.read_csv('data/equipo.csv')
df2.head()

,idEquipo,Escudo,Nombre,Pais,T,PJ,PG,PE,PP,%,Títulos,F,1/2,1/4,1/8,1/16,GF,GC,TA,TR
0,1,NaN,Real Madrid,España,54,483,292,81,110,60%16%24%,14,3,15,6,15,1,1064,528,603,25
1,2,NaN,Milan,Italia,31,273,133,70,70,48%25%27%,7,4,3,4,7,1,442,261,419,15
2,3,NaN,Bayern München,Alemania,40,389,234,77,78,60%19%21%,6,5,9,13,5,1,816,380,569,25
3,4,NaN,Liverpool,Inglaterra,27,248,142,50,56,57%20%23%,6,4,2,5,5,2,472,228,249,6
4,5,NaN,Barcelona,España,34,346,201,77,68,58%22%20%,5,3,9,7,4,0,680,350,532,17

In [21]:
#Diccionario equipos
diccionario_equipos = df2.set_index('Nombre')['idEquipo'].to_dict()
print(diccionario_equipos)

{'Real Madrid': 1, 'Milan': 2, 'Bayern München': 3, 'Liverpool': 4, 'Barcelona': 5, 'Ajax': 6, 'Inter': 7, 'Manchester United': 8, 'Juventus': 9, 'Benfica': 10, 'Chelsea': 11, 'Porto': 12, 'Nottingham Forest': 13, 'Borussia Dortmund': 14, 'Celtic': 15, 'Manchester City': 16, 'Olympique de Marseille': 17, 'FCSB': 18, 'Hamburger': 19, 'Crvena Zvezda': 20, 'PSV': 21, 'Feyenoord': 22, 'Aston Villa': 23, 'Atlético de Madrid': 24, 'Valencia': 25, 'Stade de Reims': 26, 'Monaco': 27, 'PSG': 28, 'Panathinaikos': 29, 'Leeds': 30, 'Arsenal': 31, 'Roma': 32, 'Tottenham': 33, 'Borussia Mönchengladbach': 34, 'Saint-Étienne': 35, 'Partizan': 36, 'Bayer Leverkusen': 37, 'Brugge': 38, 'Fiorentina': 39, 'Malmö': 40, 'Eintracht Frankfurt': 41, 'Sampdoria': 42, 'Dynamo Kyiv': 43, 'Anderlecht': 44, 'CSKA Sofia': 45, 'Olympique Lyonnais': 46, 'Villarreal': 47, 'Zürich': 48, 'Rangers': 49, 'Galatasaray': 50, 'Rapid Wien': 51, 'Dukla Praha': 52, 'Standard Liège': 53, 'Göteborg': 54, 'Schalke 04': 55, 'Újpest': 56, 'Spartak Moskva': 57, 'Spartak Trnava': 58, 'Legia Warszawa': 59, 'Girondins de Bordeaux': 60, 'Deportivo de La Coruña': 61, 'Austria Wien': 62, 'Vasas': 63, 'Köln': 64, 'Dinamo București': 65, 'Nantes': 66, 'Young Boys': 67, 'RB Leipzig': 68, 'Real Sociedad': 69, 'Győr': 70, 'Derby County': 71, 'Widzew Łódź': 72, 'Dundee United': 73, 'Dundee': 74, 'Hibernian': 75, 'Sparta Praha': 76, 'Dynamo Dresden': 77, 'Hajduk Split': 78, 'Dynamo Berlin': 79, 'Sevilla': 80, 'Grasshopper': 81, 'Nice': 82, 'Dnipro': 83, 'Wiener SC': 84, 'Olympiacos': 85, 'Górnik Zabrze': 86, 'Sporting de Portugal': 87, 'Fenerbahçe': 88, 'Basel': 89, 'Napoli': 90, 'AGF': 91, 'Shakhtar Donetsk': 92, 'Werder Bremen': 93, 'Beşiktaş': 94, 'AEK': 95, 'Vorwärts Berlin': 96, 'Ferencváros': 97, 'CSKA Moskva': 98, 'Lazio': 99, 'Baník Ostrava': 100, 'Wismut Aue': 101, 'Linfield': 102, 'Rosenborg': 103, 'Ruch Chorzów': 104, 'Athletic Club': 105, 'MTK Budapest': 106, 'Aberdeen': 107, 'Atalanta': 108, 'Wolverhampton': 109, 'APOEL': 110, 'SSW Innsbruck': 111, 'Kuusysi': 112, 'Brøndby': 113, 'Djurgården': 114, 'Universitatea Craiova': 115, 'Vojvodina': 116, 'Nürnberg': 117, 'Carl Zeiss Jena': 118, 'Åtvidabergs': 119, 'Everton': 120, 'Wisła Kraków': 121, 'Wolfsburg': 122, 'Auxerre': 123, 'Kaiserslautern': 124, 'Málaga': 125, 'Leicester': 126, 'Ararat Yerevan': 127, 'DWS': 128, 'Dinamo Minsk': 129, 'IFK Malmö': 130, 'Strasbourg': 131, 'Sparta Rotterdam': 132, 'KV Mechelen': 133, 'Eintracht Braunschweig': 134, 'Burnley': 135, 'Hradec Králové': 136, 'Omonia': 137, 'Budapest Honvéd': 138, 'Servette': 139, 'Zenit': 140, 'Norrköping': 141, 'Levski Sofia': 142, "Jeunesse d'Esch": 143, 'Helsinki': 144, 'Glentoran': 145, 'Tirana': 146, 'Slovan Bratislava': 147, 'Lillestrøm': 148, 'Vejle': 149, 'Esbjerg': 150, 'Stuttgart': 151, 'Magdeburg': 152, 'København': 153, 'Lille': 154, 'Swarovski Tirol': 155, 'Neuchâtel Xamax': 156, 'Argeș Pitești': 157, 'Lokomotiv Sofia': 158, 'Valur': 159, 'Trabzonspor': 160, 'Sliema Wanderers': 161, 'Dundalk': 162, 'ÍA': 163, 'Waterford': 164, 'Haka': 165, 'KB': 166, 'Lyn': 167, 'Lech Poznań': 168, 'Vålerenga': 169, 'Reipas': 170, 'B1903': 171, 'Hvidovre': 172, 'Fredrikstad': 173, 'TPS': 174, 'B1909': 175, 'PAOK': 176, 'Sarajevo': 177, 'Bohemians': 193, 'Polonia Bytom': 179, 'Beveren': 180, 'Gwardia Warszawa': 181, 'Derry City': 182, 'UTA Arad': 183, 'Red Bull Salzburg': 184, 'Dinamo Tbilisi': 185, 'Lokomotiv Moskva': 186, 'Inter Bratislava': 187, 'Gent': 188, 'AZ Alkmaar': 189, 'Celta de Vigo': 190, 'Royal Antwerp': 191, '1860 München': 192, 'Ipswich Town': 194, 'Lyngby': 195, 'Zaria': 196, 'Vítkovice': 197, 'Hellas Verona': 198, 'Cagliari': 199, 'Molenbeek': 200, 'B 1913': 201, 'Rapid București': 202, 'Zbrojovka Brno': 203, 'La Chaux-de-Fonds': 204, 'Kilmarnock': 205, 'Torino': 206, 'AB': 207, 'Spartak Plovdiv': 208, 'Szombierki Byton': 209, 'Saarbrücken': 210, 'Rot-Weiss Essen': 211, 'Rapid JC': 212, 'Cork Celtic': 213, 'HPS': 214, 'Shamrock Rovers': 215, 'Partizani': 216, 'Hibernians': 217, 'Floriana': 218, 'Viking': 219, 'Valletta': 220, 'Östers': 221, 'Avenir': 222, 'Keflavík': 223, 'KR': 224, 'Dinamo Tirana': 225, 'Odense': 226, 'Petrolul Ploiești': 227, 'Ħamrun': 228, 'Spora': 229, 'Drumcondra': 230, 'Fram': 231, 'KuPS': 232, 'Olympiakos Nicosia': 233, 'Aris Bonnevoie': 234, 'Dinamo Zagreb': 235, 'Halmstad': 236, 'Víkingur Reykjavík': 237, 'Heart of Midlothian': 238, 'Crusaders': 239, 'Trakia Plovdiv': 240, 'Torpedo Moskva': 241, 'Athlone Town': 242, 'OPS': 243, 'Progrès': 244, 'Union Luxembourg': 245, 'Rabat Ajax': 246, 'Stal Mielec': 247, 'HIFK Helsinki': 248, 'Start': 249, 'Limerick': 250, 'Stade Dudelange': 251, 'Anorthosis': 252, 'Vardar': 253, 'AEL': 254, 'Shelbourne': 255, 'Željezničar': 256, 'ŁKS': 257, 'Vllaznia': 258, 'ÍBV': 259, 'LASK': 260, 'Lierse': 261, 'Śląsk Wrocław': 262, 'Bologna': 263, 'Elbasani': 264, 'KA': 265, 'Larissa': 266, 'Red Boys Differdange': 267, "St Patrick's": 268, 'Portadown': 269, 'Glenavon': 270, 'VOËST Linz': 271, 'Distillery': 272, 'Beroe': 273, 'Csepel': 274, 'Skeid': 275, 'Admira Energie': 276, 'Lausanne': 277, 'Strømsgodset': 278, 'Sligo Rovers': 279, 'Cork Hibernians': 280, 'Køge': 281, 'KPV': 282, 'EPA Larnaca': 283, 'Karl-Marx-Stadt': 284, 'Coleraine': 285, 'Chemie Leipzig': 286, 'Ilves': 287, 'Örgryte': 288, 'Ards': 289, 'Luzern': 290, 'Pezoporikos': 291, 'Moss': 292, 'DOS': 293, 'BATE Borisov': 294, 'Sheriff Tiraspol': 295, 'Maribor': 296, 'Ludogorets': 297, 'Maccabi Haifa': 298, 'Viktoria Plzeň': 299, 'Qarabağ': 300, 'Cluj': 301, 'Skonto': 302, 'Maccabi Tel Aviv': 303, 'Sturm Graz': 304, 'Slavia Praha': 305, 'Astana': 306, 'Newcastle': 307, 'Braga': 308, 'FBK Kaunas': 309, 'Debrecen': 310, 'Molde': 311, 'Dudelange': 312, 'The New Saints': 313, 'Pyunik': 314, 'Žalgiris': 315, 'Žilina': 316, "Hapoel Be'er Sheva": 317, 'Litex Lovech': 318, 'Levadia Tallinn': 319, 'Boavista': 320, 'Midtjylland': 321, 'Aalborg': 322, 'Petržalka': 323, 'Neftçi': 324, 'Aktobe': 325, 'AIK Solna': 326, 'Zimbru': 327, 'Lens': 328, 'Helsingborg': 329, 'Lincoln Red Imps': 330, 'Skënderbeu': 331, 'Beitar Jerusalem': 332, 'Parma': 333, 'Ventspils': 334, 'Košice': 335, 'Genk': 336, 'Hafnarfjarðar': 337, 'Ekranas': 338, 'Hapoel Tel Aviv': 339, 'Torpedo Kutaisi': 340, 'Grazer AK': 341, 'Raków': 342, 'Tampere United': 343, 'Gorica': 344, 'Breiðablik': 345, 'Rubin Kazan': 346, 'Vidi': 347, 'Flora': 348, 'KÍ': 349, 'Udinese': 350, 'Elfsborg': 351, 'Krasnodar': 352, 'Olimpija': 353, 'Mallorca': 354, 'Thun': 355, 'Barry Town': 356, 'Bodø/Glimt': 357, 'Shakhter Karagandy': 358, 'Sion': 359, 'Domžale': 360, 'Zrinjski': 361, 'Rabotnički': 362, 'HB': 363, 'Alashkert': 364, 'Hertha Berliner': 365, 'Rostov': 366, 'Birkirkara': 367, 'Betis': 368, 'Shkëndija': 369, 'Kairat': 370, 'Široki Brijeg': 371, 'Olimpija Ljubljana': 372, 'Drita': 373, 'Twente': 374, 'Santa Coloma': 375, 'B36': 376, 'Slavia-Mozyr': 377, 'Unirea Urziceni': 378, 'Başakşehir': 379, 'Budućnost': 380, 'Rijeka': 381, 'Slovan Liberec': 382, 'Bakı': 383, 'Kiryat Shmona': 384, 'Häcken': 385, 'Cork City': 386, 'Apollon Limassol': 387, 'Nõmme Kalju': 388, 'Trenčín': 389, 'Víkingur Gøta': 390, 'Rudar Pljevlja': 391, 'Astana 64': 392, 'Polonia Warszawa': 393, 'Feronikeli': 394, 'MYPA': 395, 'Obilić': 396, 'Drogheda': 397, 'Mura': 398, 'Mogren': 399, "Inter d'Escaldes": 400, 'Milsami Orhei': 401, 'Borac Banja Luka': 402, 'Prishtina': 403, 'Jazz': 404, 'Aris Limassol': 405, 'Zalaegerszeg': 406, 'Modriča': 407, 'Urartu': 408, 'Dinamo Brest': 409, 'Sloga Jugomagnat': 410, 'Kukësi': 411, 'Inter Baku': 412, 'Shirak': 413, 'Sūduva': 414, 'Zestafoni': 415, 'Brann': 416, 'Stabæk': 417, 'Mladá Boleslav': 418, 'Dunaferr': 419, 'Heerenveen': 420, 'Blackburn Rovers': 421, 'EB/Streymur': 422, 'WIT Georgia': 423, 'Liepājas Metalurgs': 424, 'Sileks': 425, 'Ballkani': 426, 'Tirol Innsbruck': 427, 'Leotar': 428, 'Tavriya': 429, 'Aarau': 430, 'Belshina': 431, 'Shkupi': 432, 'Metalist': 433, 'Tre Penne': 434, 'Shamkir': 435, 'Ružomberok': 436, 'Kapaz': 437, 'Saburtalo': 438, 'Zeta': 439, 'Sioni': 440, 'Zagłębie Lubin': 441, 'Europa FC': 442, 'Ararat-Armenia': 443, 'Lugano': 444, 'Farul Constanța': 445, 'NK Zagreb': 446, 'Gomel': 447, 'Sivasspor': 448, 'Brotnjo': 449, 'Dynamo Moskva': 450, 'RFS': 451, 'Cwmbran Town': 452, 'Celje': 453, 'Llanelli Town': 454, 'Viitorul': 455, 'St Gilloise': 456, 'Hansa Rostock': 457, 'Koper': 458, 'Kalmar': 459, 'Dacia Chișinău': 460, 'NSÍ': 461, 'Universitatea Craiova FC': 462, 'Sutjeska': 463, 'Hoffenheim': 464, 'Riga': 465, 'Politehnica Timișoara': 466, 'Tre Fiori': 467, 'Fola Esch': 468, 'Montpellier': 469, 'Union Berlin': 470, 'Willem II': 471, 'Tobol': 472, 'Hapoel Haifa': 473, 'Pobeda': 474, 'Sant Julià': 475, 'Spartaks Jūrmala': 476, 'Olimpi Rustavi': 477, 'Vaslui': 478, 'AEK Larnaca': 479, 'Osasuna': 480, 'Flamurtari': 481, 'Nordsjælland': 482, 'Shakhtyor Soligorsk': 483, 'Bursaspor': 484, 'Rennes': 485, 'La Fiorita': 486, 'Cliftonville': 487, 'Kareda': 488, 'Norma Tallinn': 489, 'Lusitans': 490, "Connah's Quay": 491, 'Etar': 492, 'Silkeborg': 493, 'Swift Hesperange': 494, 'Constructorul Chişinău': 495, 'Vitória de Guimarães': 496, 'St. Gallen': 497, 'Dinamo Batumi': 498, 'Metz': 499, 'Dnipro-1': 500, 'Larne': 501, 'VB Vágur': 502, 'TVMK': 503, 'SJK': 504, 'Hammarby': 505, 'Khazar Lankaran': 506, 'Irtysh': 507, 'Astra': 508, 'ChievoVerona': 509, 'Grevenmacher': 510, 'Piast': 511, 'Struga': 512, 'Oțelul Galați': 513, 'Murata': 514, 'Rhyl': 515, 'Araks Ararat': 516, 'Folgore': 517, 'TSC Bačka Topola': 518, 'Herfølge BK': 519, 'Valmiera': 520, "Rànger's": 521, 'Toulouse': 522, 'Dnepr': 523, 'Lokomotiv Plovdiv': 524, 'Teplice': 525, 'Marsaxlokk': 526, 'Samtredia': 527, 'Alania Vladikavkaz': 528, 'Kilikija': 529, 'Liepāja': 530, 'Mladost Podgorica': 531, 'Dila': 532, 'Stjarnan': 533, 'Daugava Daugavpils': 534, 'Zulte Waregem': 535, 'Paços de Ferreira': 536, 'Ulisses': 537, 'FC Yerevan': 538, 'FCI Tallinn': 539, 'Motherwell': 540, 'Renova': 541, 'Makedonija': 542, 'Teuta': 543, 'B68': 544, 'Vác': 545, 'Inter Turku': 546, 'Mariehamn': 547, 'GÍ': 548, 'Lantana': 549, 'Bangor City': 550, "Trepça'89": 551, 'Lokomotiva Zagreb': 552, 'Atlètic Escaldes': 553}

### Partido.csv

- Añadir id por partido
- Eliminar columnas que no nos sirven
- Añadir id en local y visitante en vez de el nombre del equipo
- Añadir columnas bool victoria local, victoria visitante, empate

In [4]:
df3 = pd.read_csv('data/partido.csv')
df3.head(260)

,Temporada,Ronda,Wk,Dia,Fecha,Hora,Local,Resultado,Visitante,Público,Evento,Arbitro,Reporte,Notas
0,Temporada,Round,Wk,Day,Date,Time,Home,Score,Away,Attendance,Venue,Referee,Match Report,Notes
1,2022-2023,Group stage,1,Tue,2022-09-06,18:45,Dinamo Zagrebhr,1–0,engChelsea,"20,607",Stadion Maksimir,István Kovács,Match Report,NaN
2,2022-2023,Group stage,1,Tue,2022-09-06,18:45,Dortmundde,3–0,dkFC Copenhagen,"70,700",Signal Iduna Park,François Letexier,Match Report,NaN
3,2022-2023,Group stage,1,Tue,2022-09-06,20:00,Celticsct,0–3,esReal Madrid,"57,057",Celtic Park,Sandro Schärer,Match Report,NaN
4,2022-2023,Group stage,1,Tue,2022-09-06,20:00,Benficapt,2–0,ilMaccabi Haifa,"55,130",Estádio do Sport Lisboa e Benfica,Andreas Ekberg,Match Report,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,2021-2022,Quarter-finals,NaN,Wed,2022-04-06,21:00,Villarreales,1–0,deBayern Munich,"21,626",Estadio de la Cerámica,Anthony Taylor,Match Report,Leg 1 of 2
256,2021-2022,Quarter-finals,NaN,Tue,2022-04-12,21:00,Bayern Munichde,1–1,esVillarreal,"70,000",Allianz Arena,Slavko Vinčič,Match Report,Leg 2 of 2; Villarreal won
257,2021-2022,Quarter-finals,NaN,Tue,2022-04-12,21:00,Real Madrides,2–3,engChelsea,"59,839",Estadio Santiago Bernabéu,Szymon Marciniak,Match Report,Leg 2 of 2; Real Madrid won; Required Extra Time
258,2021-2022,Quarter-finals,NaN,Wed,2022-04-13,20:00,Liverpooleng,3–3,ptBenfica,"51,373",Anfield,Serdar Gözübüyük,Match Report,Leg 2 of 2; Liverpool won
259,2021-2022,Quarter-finals,NaN,Wed,2022-04-13,21:00,Atlético Madrides,0–0,engManchester City,"65,675",Estadio Wanda Metropolitano,Daniel Siebert,Match Report,Leg 2 of 2; Manchester City won

### Trayectoria_entrenador.csv

- IdEquipo en vez de el nombre
- Eliminar columnas que no nos sirven

In [5]:
df4 = pd.read_csv('data/Trayectoria_entrenador.csv')
df4.head(150)

,idEntrenador,Temporada,Equipo,Nun,Non,División,Edad,PJ,PG,PE,PP,Non.1
0,1,1978-79,Aberdeen,NaN,NaN,NaN,37,-,-,-,-,NaN
1,1,1979-80,Aberdeen,NaN,NaN,NaN,38,-,-,-,-,NaN
2,1,1980-81,Aberdeen,NaN,NaN,NaN,39,-,-,-,-,NaN
3,1,1981-82,Aberdeen,NaN,NaN,NaN,40,-,-,-,-,NaN
4,1,1982-83,Aberdeen,NaN,NaN,NaN,41,-,-,-,-,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
145,6,2006-07,Chelsea,NaN,NaN,1ª,43,38,24,11,3,NaN
146,6,2007-08,Chelsea,NaN,NaN,1ª,44,6,3,2,1,NaN
147,6,2008-09,Inter,NaN,NaN,1ª,45,38,25,9,4,NaN
148,6,2009-10,Inter,NaN,NaN,1ª,46,38,24,10,4,NaN
149,6,2010-11,Real Madrid,NaN,NaN,1ª,47,38,29,5,4,NaN

### Jugador.csv

In [34]:
df5 = pd.read_csv('data/jugador.csv')
df5.head(700)

,Temporada,#,Jugador,País,Posc,Equipo,Edad,Nacimiento,PJ,Titular,...,TP,TPint,TA,TR,Gls.90,Ast90,G+A90,G-TP90,G+A-TP90,Partidos
0,1992-1993,1,Berry van Aerle,nlNED,"DF,CC",nlPSV,29,1962,6,6,...,0,NaN,2,0,0.00,NaN,NaN,0.00,NaN,Partidos
1,1992-1993,2,Giorgos Agorogiannis,grGRE,DF,grAEK Athens,26,1966,3,1,...,0,NaN,1,0,0.00,NaN,NaN,0.00,NaN,Partidos
2,1992-1993,3,Ernst Aigner,atAUT,DF,atAustria Wien,25,1966,3,3,...,0,NaN,3,0,0.00,NaN,NaN,0.00,NaN,Partidos
3,1992-1993,4,Kadir Akbulut,trTUR,"DF,CC",trBeşiktaş,32,1960,2,2,...,0,NaN,0,0,0.00,NaN,NaN,0.00,NaN,Partidos
4,1992-1993,5,Flórián Albert Jr.,huHUN,CC,huFerencváros,24,1967,2,2,...,0,NaN,0,0,0.00,NaN,NaN,0.00,NaN,Partidos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1993-1994,139,David Galea,NaN,NaN,mtFloriana FC,20,1973,1,1,...,0,NaN,0,0,0.00,NaN,NaN,0.00,NaN,Partidos
696,1993-1994,140,Filippo Galli,itITA,DF,itMilan,30,1963,6,3,...,0,NaN,0,0,0.00,NaN,NaN,0.00,NaN,Partidos
697,1993-1994,141,Josip Gašpar,hrCRO,CC,hrCroatia Zagreb,20,1973,1,1,...,0,NaN,0,0,0.00,NaN,NaN,0.00,NaN,Partidos
698,1993-1994,142,Tommy Gaynor,ieIRL,DL,ieCork City FC,30,1963,2,2,...,0,NaN,0,0,0.00,NaN,NaN,0.00,NaN,Partidos
699,1993-1994,143,Ryan Giggs,wlsWAL,"DL,CC",engManchester Utd,19,1973,4,4,...,0,NaN,0,0,0.00,NaN,NaN,0.00,NaN,Partidos

In [10]:
df6 = pd.read_csv('data/jugador2.csv')
df6.head(10)

,Temporada,#,Jugador,País,Posc,Equipo,Edad,Nacimiento,PJ,Titular,...,Ast90,G+A90,G-TP90,G+A-TP90,xG90,xAG90,xG+xAG90,npxG90,npxG+xAG90,Partidos
0,2017-2018,1,Vincent Aboubakar,cmCMR,DL,ptPorto,25,1992,6,6,...,0.36,1.27,0.91,1.27,0.51,0.19,0.70,0.51,0.70,Partidos
1,2017-2018,2,Marcos Acuña,arARG,"DL,DF",ptSporting CP,25,1991,5,5,...,0.21,0.21,0.00,0.21,0.00,0.11,0.11,0.00,0.11,Partidos
2,2017-2018,3,Tosin Adarabioyo,engENG,DF,engManchester City,19,1997,2,1,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Partidos
3,2017-2018,4,Adriano,brBRA,DF,trBeşiktaş,32,1984,6,5,...,0.00,0.00,0.00,0.00,0.01,0.02,0.03,0.01,0.03,Partidos
4,2017-2018,5,Luiz Adriano,brBRA,"DL,CC",ruSpartak Moscow,30,1987,6,6,...,0.00,0.17,0.17,0.17,0.16,0.15,0.32,0.16,0.32,Partidos
5,2017-2018,6,Ansi Agolli,alALB,DF,azQarabağ FK,34,1982,4,4,...,0.00,0.00,0.00,0.00,0.01,0.03,0.04,0.01,0.04,Partidos
6,2017-2018,7,Sergio Agüero,arARG,DL,engManchester City,29,1988,7,5,...,0.20,1.02,0.61,0.82,0.80,0.08,0.88,0.49,0.57,Partidos
7,2017-2018,8,Karim El Ahmadi,maMAR,CC,nlFeyenoord,32,1985,4,4,...,0.00,0.00,0.00,0.00,0.03,0.08,0.11,0.03,0.11,Partidos
8,2017-2018,9,Valon Ahmedi,alALB,"CC,DL",siNK Maribor,22,1994,4,3,...,0.00,0.00,0.00,0.00,0.10,0.21,0.31,0.10,0.31,Partidos
9,2017-2018,10,Albian Ajeti,chSUI,DL,chBasel,20,1997,3,1,...,0.00,0.00,0.00,0.00,0.12,0.00,0.12,0.12,0.12,Partidos